packages:
  - 'apps/storefront'
  - 'apps/admin'
  - 'apps/checkin'
  - 'packages/api-client'
  - 'packages/ui'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  sharp: true
  unrs-resolver: true
