<?php

use App\Support\Problems\ErrorCode;

test('the registry holds exactly the known codes', function () {
    expect(array_map(fn (ErrorCode $code) => $code->value, ErrorCode::cases()))->toBe([
        'request.not_found',
        'request.method_not_allowed',
        'request.validation_failed',
        'auth.unauthenticated',
        'auth.forbidden',
        'request.rate_limited',
        'payload_too_large',
        'server.internal_error',
        'health.degraded',
        'invalid_query_parameter',
        'tenant_not_found',
        'default_locale_not_supported',
        'tenant_domain_not_found',
        'domain_already_registered',
        'tenant_domain_is_primary',
        'unknown_host',
        'missing_tenant_header',
        'invalid_tenant_header',
        'tenant_access_denied',
        'unknown_domain',
        'invalid_credentials',
        'invalid_refresh_token',
        'refresh_token_reused',
        'missing_capability',
        'role_not_editable',
        'role_in_use',
        'role_name_taken',
        'unknown_capability',
        'membership_exists',
        'last_owner_removal',
        'invitation_token_invalid',
        'invitation_token_expired',
        'mfa_required',
        'mfa_code_invalid',
        'mfa_already_enrolled',
        'mfa_not_enrolled',
        'mfa_enforced_for_role',
        'mfa_enforcement_required',
        'tenant_mismatch',
        'customer_email_taken',
        'customer_already_claimed',
        'claim_token_invalid',
        'claim_token_expired',
        'reset_token_invalid',
        'reset_token_expired',
        'catalog.event_immutable',
        'catalog.currency_mismatch',
        'catalog.event_not_publishable',
        'catalog.event_not_cancelable',
        'catalog.seat_map_duplicate_seats',
        'catalog.seat_map_name_taken',
        'catalog.seat_map_conflict',
        'catalog.seat_map_venue_mismatch',
        'catalog.seat_map_virtual_event',
        'catalog.seat_map_in_use',
        'catalog.seat_map_required',
        'insufficient_inventory',
        'event_not_found',
        'ticket_type_not_in_event',
        'sales_window_closed',
        'hold_not_found',
        'hold_not_releasable',
        'hold_not_extendable',
        'hold_not_committable',
        'seat_selection_invalid',
        'seat_unavailable',
        'event_not_seated',
        'seat_not_modifiable',
        'checkout.hold_expired',
        'hold_already_converted',
        'order_not_found',
        'order_not_cancelable',
        'order_not_paid',
        'invalid_order_transition',
        'promo_code_invalid',
        'promo_code_not_active',
        'promo_code_exhausted',
        'promo_code_currency_mismatch',
        'promo_code_immutable_field',
        'idempotency_key_missing',
        'idempotency_key_reuse_mismatch',
        'order_not_payable',
        'payment_method_not_available',
        'payment_declined',
        'gateway_unavailable',
        'webhook_signature_invalid',
        'webhook_unparseable',
        'refund_payment_not_found',
        'refund_not_found',
        'payment_not_refundable',
        'refund_amount_exceeds_refundable',
        'refund_currency_mismatch',
        'refund_tickets_not_in_order',
        'gateway_unknown',
        'gateway_not_enabled',
        'gateway_not_configured',
        'submerchant_already_onboarded',
        'submerchant_not_active',
        'checkin_not_assigned',
        'qr_signature_invalid',
        'qr_key_revoked',
        'ticket_rotation_stale',
        'scanned_at_in_future',
        'ticket_not_found',
        'ticket_canceled',
        'ticket_refunded',
        'ticket_already_checked_in',
        'batch_too_large',
        'user_not_member',
        'already_assigned',
        'assignment_not_found',
        'customer_required',
        'purchase_limit_exceeded',
        'queue_not_active',
        'challenge_required',
        'challenge_failed',
        'queue_entry_not_found',
        'admission_required',
        'admission_invalid',
    ]);
});

test('every error code maps to its status, title, and type slug', function (ErrorCode $code, int $status, string $title, string $type) {
    expect($code->status())->toBe($status)
        ->and($code->title())->toBe($title)
        ->and($code->type())->toBe($type);
})->with([
    'request.not_found' => [ErrorCode::RequestNotFound, 404, 'Not found', '/problems/request-not-found'],
    'request.method_not_allowed' => [ErrorCode::RequestMethodNotAllowed, 405, 'Method not allowed', '/problems/request-method-not-allowed'],
    'request.validation_failed' => [ErrorCode::RequestValidationFailed, 422, 'Validation failed', '/problems/request-validation-failed'],
    'auth.unauthenticated' => [ErrorCode::AuthUnauthenticated, 401, 'Unauthenticated', '/problems/auth-unauthenticated'],
    'auth.forbidden' => [ErrorCode::AuthForbidden, 403, 'Forbidden', '/problems/auth-forbidden'],
    'request.rate_limited' => [ErrorCode::RequestRateLimited, 429, 'Too many requests', '/problems/request-rate-limited'],
    'payload_too_large' => [ErrorCode::PayloadTooLarge, 413, 'Payload too large', '/problems/payload-too-large'],
    'server.internal_error' => [ErrorCode::ServerInternalError, 500, 'Internal server error', '/problems/server-internal-error'],
    'health.degraded' => [ErrorCode::HealthDegraded, 503, 'Service degraded', '/problems/health-degraded'],
    'invalid_query_parameter' => [ErrorCode::InvalidQueryParameter, 400, 'Invalid query parameter', '/problems/invalid-query-parameter'],
    'tenant_not_found' => [ErrorCode::TenantNotFound, 404, 'Tenant not found', '/problems/tenant-not-found'],
    'default_locale_not_supported' => [ErrorCode::DefaultLocaleNotSupported, 422, 'Default locale not supported', '/problems/default-locale-not-supported'],
    'tenant_domain_not_found' => [ErrorCode::TenantDomainNotFound, 404, 'Tenant domain not found', '/problems/tenant-domain-not-found'],
    'domain_already_registered' => [ErrorCode::DomainAlreadyRegistered, 409, 'Domain already registered', '/problems/domain-already-registered'],
    'tenant_domain_is_primary' => [ErrorCode::TenantDomainIsPrimary, 409, 'Tenant domain is primary', '/problems/tenant-domain-is-primary'],
    'unknown_host' => [ErrorCode::UnknownHost, 404, 'Unknown host', '/problems/unknown-host'],
    'missing_tenant_header' => [ErrorCode::MissingTenantHeader, 400, 'Missing tenant header', '/problems/missing-tenant-header'],
    'invalid_tenant_header' => [ErrorCode::InvalidTenantHeader, 400, 'Invalid tenant header', '/problems/invalid-tenant-header'],
    'tenant_access_denied' => [ErrorCode::TenantAccessDenied, 403, 'Tenant access denied', '/problems/tenant-access-denied'],
    'unknown_domain' => [ErrorCode::UnknownDomain, 404, 'Unknown domain', '/problems/unknown-domain'],
    'invalid_credentials' => [ErrorCode::InvalidCredentials, 401, 'Invalid credentials', '/problems/invalid-credentials'],
    'invalid_refresh_token' => [ErrorCode::InvalidRefreshToken, 401, 'Invalid refresh token', '/problems/invalid-refresh-token'],
    'refresh_token_reused' => [ErrorCode::RefreshTokenReused, 401, 'Refresh token reused', '/problems/refresh-token-reused'],
    'missing_capability' => [ErrorCode::MissingCapability, 403, 'Missing capability', '/problems/missing-capability'],
    'role_not_editable' => [ErrorCode::RoleNotEditable, 409, 'Role not editable', '/problems/role-not-editable'],
    'role_in_use' => [ErrorCode::RoleInUse, 409, 'Role in use', '/problems/role-in-use'],
    'role_name_taken' => [ErrorCode::RoleNameTaken, 409, 'Role name taken', '/problems/role-name-taken'],
    'unknown_capability' => [ErrorCode::UnknownCapability, 422, 'Unknown capability', '/problems/unknown-capability'],
    'membership_exists' => [ErrorCode::MembershipExists, 409, 'Membership exists', '/problems/membership-exists'],
    'last_owner_removal' => [ErrorCode::LastOwnerRemoval, 409, 'Last owner removal', '/problems/last-owner-removal'],
    'invitation_token_invalid' => [ErrorCode::InvitationTokenInvalid, 401, 'Invitation token invalid', '/problems/invitation-token-invalid'],
    'invitation_token_expired' => [ErrorCode::InvitationTokenExpired, 401, 'Invitation token expired', '/problems/invitation-token-expired'],
    'mfa_required' => [ErrorCode::MfaRequired, 401, 'MFA required', '/problems/mfa-required'],
    'mfa_code_invalid' => [ErrorCode::MfaCodeInvalid, 401, 'MFA code invalid', '/problems/mfa-code-invalid'],
    'mfa_already_enrolled' => [ErrorCode::MfaAlreadyEnrolled, 409, 'MFA already enrolled', '/problems/mfa-already-enrolled'],
    'mfa_not_enrolled' => [ErrorCode::MfaNotEnrolled, 409, 'MFA not enrolled', '/problems/mfa-not-enrolled'],
    'mfa_enforced_for_role' => [ErrorCode::MfaEnforcedForRole, 403, 'MFA enforced for role', '/problems/mfa-enforced-for-role'],
    'mfa_enforcement_required' => [ErrorCode::MfaEnforcementRequired, 403, 'MFA enforcement required', '/problems/mfa-enforcement-required'],
    'tenant_mismatch' => [ErrorCode::TenantMismatch, 401, 'Tenant mismatch', '/problems/tenant-mismatch'],
    'customer_email_taken' => [ErrorCode::CustomerEmailTaken, 409, 'Customer email taken', '/problems/customer-email-taken'],
    'customer_already_claimed' => [ErrorCode::CustomerAlreadyClaimed, 409, 'Customer already claimed', '/problems/customer-already-claimed'],
    'claim_token_invalid' => [ErrorCode::ClaimTokenInvalid, 401, 'Claim token invalid', '/problems/claim-token-invalid'],
    'claim_token_expired' => [ErrorCode::ClaimTokenExpired, 401, 'Claim token expired', '/problems/claim-token-expired'],
    'reset_token_invalid' => [ErrorCode::PasswordResetTokenInvalid, 401, 'Password reset token invalid', '/problems/reset-token-invalid'],
    'reset_token_expired' => [ErrorCode::PasswordResetTokenExpired, 401, 'Password reset token expired', '/problems/reset-token-expired'],
    'catalog.event_immutable' => [ErrorCode::CatalogEventImmutable, 409, 'Event immutable', '/problems/catalog-event-immutable'],
    'catalog.currency_mismatch' => [ErrorCode::CatalogCurrencyMismatch, 422, 'Currency mismatch', '/problems/catalog-currency-mismatch'],
    'catalog.event_not_publishable' => [ErrorCode::CatalogEventNotPublishable, 409, 'Event not publishable', '/problems/catalog-event-not-publishable'],
    'catalog.event_not_cancelable' => [ErrorCode::CatalogEventNotCancelable, 409, 'Event not cancelable', '/problems/catalog-event-not-cancelable'],
    'catalog.seat_map_duplicate_seats' => [ErrorCode::CatalogSeatMapDuplicateSeats, 422, 'Duplicate seats', '/problems/catalog-seat-map-duplicate-seats'],
    'catalog.seat_map_name_taken' => [ErrorCode::CatalogSeatMapNameTaken, 422, 'Seat map name taken', '/problems/catalog-seat-map-name-taken'],
    'catalog.seat_map_conflict' => [ErrorCode::CatalogSeatMapConflict, 409, 'Seat map conflict', '/problems/catalog-seat-map-conflict'],
    'catalog.seat_map_venue_mismatch' => [ErrorCode::CatalogSeatMapVenueMismatch, 422, 'Seat map venue mismatch', '/problems/catalog-seat-map-venue-mismatch'],
    'catalog.seat_map_virtual_event' => [ErrorCode::CatalogSeatMapVirtualEvent, 422, 'Seat map virtual event', '/problems/catalog-seat-map-virtual-event'],
    'catalog.seat_map_in_use' => [ErrorCode::CatalogSeatMapInUse, 409, 'Seat map in use', '/problems/catalog-seat-map-in-use'],
    'catalog.seat_map_required' => [ErrorCode::CatalogSeatMapRequired, 409, 'Seat map required', '/problems/catalog-seat-map-required'],
    'insufficient_inventory' => [ErrorCode::InsufficientInventory, 409, 'Insufficient inventory', '/problems/insufficient-inventory'],
    'event_not_found' => [ErrorCode::EventNotFound, 404, 'Event not found', '/problems/event-not-found'],
    'ticket_type_not_in_event' => [ErrorCode::TicketTypeNotInEvent, 422, 'Ticket type not in event', '/problems/ticket-type-not-in-event'],
    'sales_window_closed' => [ErrorCode::SalesWindowClosed, 409, 'Sales window closed', '/problems/sales-window-closed'],
    'hold_not_found' => [ErrorCode::HoldNotFound, 404, 'Hold not found', '/problems/hold-not-found'],
    'hold_not_releasable' => [ErrorCode::HoldNotReleasable, 409, 'Hold not releasable', '/problems/hold-not-releasable'],
    'hold_not_extendable' => [ErrorCode::HoldNotExtendable, 409, 'Hold not extendable', '/problems/hold-not-extendable'],
    'hold_not_committable' => [ErrorCode::HoldNotCommittable, 409, 'Hold not committable', '/problems/hold-not-committable'],
    'seat_selection_invalid' => [ErrorCode::SeatSelectionInvalid, 422, 'Seat selection invalid', '/problems/seat-selection-invalid'],
    'seat_unavailable' => [ErrorCode::SeatUnavailable, 409, 'Seat unavailable', '/problems/seat-unavailable'],
    'event_not_seated' => [ErrorCode::EventNotSeated, 409, 'Event not seated', '/problems/event-not-seated'],
    'seat_not_modifiable' => [ErrorCode::SeatNotModifiable, 409, 'Seat not modifiable', '/problems/seat-not-modifiable'],
    'checkout.hold_expired' => [ErrorCode::CheckoutHoldExpired, 409, 'Hold expired', '/problems/checkout-hold-expired'],
    'hold_already_converted' => [ErrorCode::HoldAlreadyConverted, 409, 'Hold already converted', '/problems/hold-already-converted'],
    'order_not_found' => [ErrorCode::OrderNotFound, 404, 'Order not found', '/problems/order-not-found'],
    'order_not_cancelable' => [ErrorCode::OrderNotCancelable, 409, 'Order not cancelable', '/problems/order-not-cancelable'],
    'order_not_paid' => [ErrorCode::OrderNotPaid, 409, 'Order not paid', '/problems/order-not-paid'],
    'invalid_order_transition' => [ErrorCode::InvalidOrderTransition, 409, 'Invalid order transition', '/problems/invalid-order-transition'],
    'promo_code_invalid' => [ErrorCode::PromoCodeInvalid, 422, 'Promo code invalid', '/problems/promo-code-invalid'],
    'promo_code_not_active' => [ErrorCode::PromoCodeNotActive, 422, 'Promo code not active', '/problems/promo-code-not-active'],
    'promo_code_exhausted' => [ErrorCode::PromoCodeExhausted, 422, 'Promo code exhausted', '/problems/promo-code-exhausted'],
    'promo_code_currency_mismatch' => [ErrorCode::PromoCodeCurrencyMismatch, 422, 'Promo code currency mismatch', '/problems/promo-code-currency-mismatch'],
    'promo_code_immutable_field' => [ErrorCode::PromoCodeImmutableField, 422, 'Promo code immutable field', '/problems/promo-code-immutable-field'],
    'idempotency_key_missing' => [ErrorCode::IdempotencyKeyMissing, 400, 'Idempotency key missing', '/problems/idempotency-key-missing'],
    'idempotency_key_reuse_mismatch' => [ErrorCode::IdempotencyKeyReuseMismatch, 409, 'Idempotency key reuse mismatch', '/problems/idempotency-key-reuse-mismatch'],
    'order_not_payable' => [ErrorCode::OrderNotPayable, 409, 'Order not payable', '/problems/order-not-payable'],
    'payment_method_not_available' => [ErrorCode::PaymentMethodNotAvailable, 422, 'Payment method not available', '/problems/payment-method-not-available'],
    'payment_declined' => [ErrorCode::PaymentDeclined, 402, 'Payment declined', '/problems/payment-declined'],
    'gateway_unavailable' => [ErrorCode::GatewayUnavailable, 503, 'Gateway unavailable', '/problems/gateway-unavailable'],
    'webhook_signature_invalid' => [ErrorCode::WebhookSignatureInvalid, 401, 'Webhook signature invalid', '/problems/webhook-signature-invalid'],
    'webhook_unparseable' => [ErrorCode::WebhookUnparseable, 422, 'Webhook unparseable', '/problems/webhook-unparseable'],
    'gateway_unknown' => [ErrorCode::GatewayUnknown, 422, 'Gateway unknown', '/problems/gateway-unknown'],
    'gateway_not_enabled' => [ErrorCode::GatewayNotEnabled, 409, 'Gateway not enabled', '/problems/gateway-not-enabled'],
    'gateway_not_configured' => [ErrorCode::GatewayNotConfigured, 409, 'Gateway not configured', '/problems/gateway-not-configured'],
    'submerchant_already_onboarded' => [ErrorCode::SubmerchantAlreadyOnboarded, 409, 'Submerchant already onboarded', '/problems/submerchant-already-onboarded'],
    'submerchant_not_active' => [ErrorCode::SubmerchantNotActive, 409, 'Submerchant not active', '/problems/submerchant-not-active'],
    'checkin_not_assigned' => [ErrorCode::CheckinNotAssigned, 403, 'Not assigned to event', '/problems/checkin-not-assigned'],
    'qr_signature_invalid' => [ErrorCode::QrSignatureInvalid, 422, 'QR signature invalid', '/problems/qr-signature-invalid'],
    'qr_key_revoked' => [ErrorCode::QrKeyRevoked, 422, 'QR key revoked', '/problems/qr-key-revoked'],
    'ticket_rotation_stale' => [ErrorCode::TicketRotationStale, 422, 'Ticket rotation stale', '/problems/ticket-rotation-stale'],
    'scanned_at_in_future' => [ErrorCode::ScannedAtInFuture, 422, 'Scanned at in future', '/problems/scanned-at-in-future'],
    'ticket_not_found' => [ErrorCode::CheckInTicketNotFound, 404, 'Ticket not found', '/problems/ticket-not-found'],
    'ticket_canceled' => [ErrorCode::CheckInTicketCanceled, 409, 'Ticket canceled', '/problems/ticket-canceled'],
    'ticket_refunded' => [ErrorCode::CheckInTicketRefunded, 409, 'Ticket refunded', '/problems/ticket-refunded'],
    'ticket_already_checked_in' => [ErrorCode::TicketAlreadyCheckedIn, 409, 'Ticket already checked in', '/problems/ticket-already-checked-in'],
    'batch_too_large' => [ErrorCode::BatchTooLarge, 422, 'Batch too large', '/problems/batch-too-large'],
    'user_not_member' => [ErrorCode::UserNotMember, 422, 'User not a member', '/problems/user-not-member'],
    'already_assigned' => [ErrorCode::AlreadyAssigned, 409, 'Already assigned', '/problems/already-assigned'],
    'assignment_not_found' => [ErrorCode::AssignmentNotFound, 404, 'Assignment not found', '/problems/assignment-not-found'],
    'customer_required' => [ErrorCode::CustomerRequired, 422, 'Customer required', '/problems/customer-required'],
    'purchase_limit_exceeded' => [ErrorCode::PurchaseLimitExceeded, 409, 'Purchase limit exceeded', '/problems/purchase-limit-exceeded'],
    'queue_not_active' => [ErrorCode::QueueNotActive, 409, 'Queue not active', '/problems/queue-not-active'],
    'challenge_required' => [ErrorCode::ChallengeRequired, 403, 'Challenge required', '/problems/challenge-required'],
    'challenge_failed' => [ErrorCode::ChallengeFailed, 403, 'Challenge failed', '/problems/challenge-failed'],
    'queue_entry_not_found' => [ErrorCode::QueueEntryNotFound, 404, 'Queue entry not found', '/problems/queue-entry-not-found'],
    'admission_required' => [ErrorCode::AdmissionRequired, 403, 'Admission required', '/problems/admission-required'],
    'admission_invalid' => [ErrorCode::AdmissionInvalid, 403, 'Admission invalid', '/problems/admission-invalid'],
]);

test('the type slug is derived mechanically from the code, dots and underscores to dashes', function () {
    foreach (ErrorCode::cases() as $code) {
        expect($code->type())->toBe('/problems/'.str_replace(['.', '_'], '-', $code->value));
    }
});
