<?php

use App\Support\Problems\ErrorCode;

test('the registry holds exactly the known codes', function () {
    expect(array_map(fn (ErrorCode $code) => $code->value, ErrorCode::cases()))->toBe([
        'request.not_found',
        'request.method_not_allowed',
        'request.validation_failed',
        'auth.unauthenticated',
        'auth.forbidden',
        'request.rate_limited',
        'server.internal_error',
        'health.degraded',
        'invalid_query_parameter',
        'tenant_not_found',
        'default_locale_not_supported',
        'tenant_domain_not_found',
        'domain_already_registered',
        'tenant_domain_is_primary',
        'unknown_host',
        'missing_tenant_header',
        'invalid_tenant_header',
        'tenant_access_denied',
        'unknown_domain',
        'invalid_credentials',
        'invalid_refresh_token',
        'refresh_token_reused',
        'missing_capability',
        'role_not_editable',
        'role_in_use',
        'role_name_taken',
        'unknown_capability',
        'membership_exists',
        'last_owner_removal',
        'invitation_token_invalid',
        'invitation_token_expired',
        'mfa_required',
        'mfa_code_invalid',
        'mfa_already_enrolled',
        'mfa_not_enrolled',
        'mfa_enforced_for_role',
        'mfa_enforcement_required',
        'tenant_mismatch',
        'customer_email_taken',
        'customer_already_claimed',
        'claim_token_invalid',
        'claim_token_expired',
        'reset_token_invalid',
        'reset_token_expired',
        'catalog.event_immutable',
        'catalog.currency_mismatch',
        'catalog.event_not_publishable',
        'catalog.event_not_cancelable',
        'catalog.seat_map_duplicate_seats',
        'catalog.seat_map_name_taken',
        'catalog.seat_map_conflict',
    ]);
});

test('every error code maps to its status, title, and type slug', function (ErrorCode $code, int $status, string $title, string $type) {
    expect($code->status())->toBe($status)
        ->and($code->title())->toBe($title)
        ->and($code->type())->toBe($type);
})->with([
    'request.not_found' => [ErrorCode::RequestNotFound, 404, 'Not found', '/problems/request-not-found'],
    'request.method_not_allowed' => [ErrorCode::RequestMethodNotAllowed, 405, 'Method not allowed', '/problems/request-method-not-allowed'],
    'request.validation_failed' => [ErrorCode::RequestValidationFailed, 422, 'Validation failed', '/problems/request-validation-failed'],
    'auth.unauthenticated' => [ErrorCode::AuthUnauthenticated, 401, 'Unauthenticated', '/problems/auth-unauthenticated'],
    'auth.forbidden' => [ErrorCode::AuthForbidden, 403, 'Forbidden', '/problems/auth-forbidden'],
    'request.rate_limited' => [ErrorCode::RequestRateLimited, 429, 'Too many requests', '/problems/request-rate-limited'],
    'server.internal_error' => [ErrorCode::ServerInternalError, 500, 'Internal server error', '/problems/server-internal-error'],
    'health.degraded' => [ErrorCode::HealthDegraded, 503, 'Service degraded', '/problems/health-degraded'],
    'invalid_query_parameter' => [ErrorCode::InvalidQueryParameter, 400, 'Invalid query parameter', '/problems/invalid-query-parameter'],
    'tenant_not_found' => [ErrorCode::TenantNotFound, 404, 'Tenant not found', '/problems/tenant-not-found'],
    'default_locale_not_supported' => [ErrorCode::DefaultLocaleNotSupported, 422, 'Default locale not supported', '/problems/default-locale-not-supported'],
    'tenant_domain_not_found' => [ErrorCode::TenantDomainNotFound, 404, 'Tenant domain not found', '/problems/tenant-domain-not-found'],
    'domain_already_registered' => [ErrorCode::DomainAlreadyRegistered, 409, 'Domain already registered', '/problems/domain-already-registered'],
    'tenant_domain_is_primary' => [ErrorCode::TenantDomainIsPrimary, 409, 'Tenant domain is primary', '/problems/tenant-domain-is-primary'],
    'unknown_host' => [ErrorCode::UnknownHost, 404, 'Unknown host', '/problems/unknown-host'],
    'missing_tenant_header' => [ErrorCode::MissingTenantHeader, 400, 'Missing tenant header', '/problems/missing-tenant-header'],
    'invalid_tenant_header' => [ErrorCode::InvalidTenantHeader, 400, 'Invalid tenant header', '/problems/invalid-tenant-header'],
    'tenant_access_denied' => [ErrorCode::TenantAccessDenied, 403, 'Tenant access denied', '/problems/tenant-access-denied'],
    'unknown_domain' => [ErrorCode::UnknownDomain, 404, 'Unknown domain', '/problems/unknown-domain'],
    'invalid_credentials' => [ErrorCode::InvalidCredentials, 401, 'Invalid credentials', '/problems/invalid-credentials'],
    'invalid_refresh_token' => [ErrorCode::InvalidRefreshToken, 401, 'Invalid refresh token', '/problems/invalid-refresh-token'],
    'refresh_token_reused' => [ErrorCode::RefreshTokenReused, 401, 'Refresh token reused', '/problems/refresh-token-reused'],
    'missing_capability' => [ErrorCode::MissingCapability, 403, 'Missing capability', '/problems/missing-capability'],
    'role_not_editable' => [ErrorCode::RoleNotEditable, 409, 'Role not editable', '/problems/role-not-editable'],
    'role_in_use' => [ErrorCode::RoleInUse, 409, 'Role in use', '/problems/role-in-use'],
    'role_name_taken' => [ErrorCode::RoleNameTaken, 409, 'Role name taken', '/problems/role-name-taken'],
    'unknown_capability' => [ErrorCode::UnknownCapability, 422, 'Unknown capability', '/problems/unknown-capability'],
    'membership_exists' => [ErrorCode::MembershipExists, 409, 'Membership exists', '/problems/membership-exists'],
    'last_owner_removal' => [ErrorCode::LastOwnerRemoval, 409, 'Last owner removal', '/problems/last-owner-removal'],
    'invitation_token_invalid' => [ErrorCode::InvitationTokenInvalid, 401, 'Invitation token invalid', '/problems/invitation-token-invalid'],
    'invitation_token_expired' => [ErrorCode::InvitationTokenExpired, 401, 'Invitation token expired', '/problems/invitation-token-expired'],
    'mfa_required' => [ErrorCode::MfaRequired, 401, 'MFA required', '/problems/mfa-required'],
    'mfa_code_invalid' => [ErrorCode::MfaCodeInvalid, 401, 'MFA code invalid', '/problems/mfa-code-invalid'],
    'mfa_already_enrolled' => [ErrorCode::MfaAlreadyEnrolled, 409, 'MFA already enrolled', '/problems/mfa-already-enrolled'],
    'mfa_not_enrolled' => [ErrorCode::MfaNotEnrolled, 409, 'MFA not enrolled', '/problems/mfa-not-enrolled'],
    'mfa_enforced_for_role' => [ErrorCode::MfaEnforcedForRole, 403, 'MFA enforced for role', '/problems/mfa-enforced-for-role'],
    'mfa_enforcement_required' => [ErrorCode::MfaEnforcementRequired, 403, 'MFA enforcement required', '/problems/mfa-enforcement-required'],
    'tenant_mismatch' => [ErrorCode::TenantMismatch, 401, 'Tenant mismatch', '/problems/tenant-mismatch'],
    'customer_email_taken' => [ErrorCode::CustomerEmailTaken, 409, 'Customer email taken', '/problems/customer-email-taken'],
    'customer_already_claimed' => [ErrorCode::CustomerAlreadyClaimed, 409, 'Customer already claimed', '/problems/customer-already-claimed'],
    'claim_token_invalid' => [ErrorCode::ClaimTokenInvalid, 401, 'Claim token invalid', '/problems/claim-token-invalid'],
    'claim_token_expired' => [ErrorCode::ClaimTokenExpired, 401, 'Claim token expired', '/problems/claim-token-expired'],
    'reset_token_invalid' => [ErrorCode::PasswordResetTokenInvalid, 401, 'Password reset token invalid', '/problems/reset-token-invalid'],
    'reset_token_expired' => [ErrorCode::PasswordResetTokenExpired, 401, 'Password reset token expired', '/problems/reset-token-expired'],
    'catalog.event_immutable' => [ErrorCode::CatalogEventImmutable, 409, 'Event immutable', '/problems/catalog-event-immutable'],
    'catalog.currency_mismatch' => [ErrorCode::CatalogCurrencyMismatch, 422, 'Currency mismatch', '/problems/catalog-currency-mismatch'],
    'catalog.event_not_publishable' => [ErrorCode::CatalogEventNotPublishable, 409, 'Event not publishable', '/problems/catalog-event-not-publishable'],
    'catalog.event_not_cancelable' => [ErrorCode::CatalogEventNotCancelable, 409, 'Event not cancelable', '/problems/catalog-event-not-cancelable'],
    'catalog.seat_map_duplicate_seats' => [ErrorCode::CatalogSeatMapDuplicateSeats, 422, 'Duplicate seats', '/problems/catalog-seat-map-duplicate-seats'],
    'catalog.seat_map_name_taken' => [ErrorCode::CatalogSeatMapNameTaken, 422, 'Seat map name taken', '/problems/catalog-seat-map-name-taken'],
    'catalog.seat_map_conflict' => [ErrorCode::CatalogSeatMapConflict, 409, 'Seat map conflict', '/problems/catalog-seat-map-conflict'],
]);

test('the type slug is derived mechanically from the code, dots and underscores to dashes', function () {
    foreach (ErrorCode::cases() as $code) {
        expect($code->type())->toBe('/problems/'.str_replace(['.', '_'], '-', $code->value));
    }
});
