<?php

namespace App\Support\Problems;

use Spatie\TypeScriptTransformer\Attributes\TypeScript;

#[TypeScript]
enum ErrorCode: string
{
    case RequestNotFound = 'request.not_found';
    case RequestMethodNotAllowed = 'request.method_not_allowed';
    case RequestValidationFailed = 'request.validation_failed';
    case AuthUnauthenticated = 'auth.unauthenticated';
    case AuthForbidden = 'auth.forbidden';
    case RequestRateLimited = 'request.rate_limited';
    case PayloadTooLarge = 'payload_too_large';
    case ServerInternalError = 'server.internal_error';
    case HealthDegraded = 'health.degraded';
    case InvalidQueryParameter = 'invalid_query_parameter';
    case TenantNotFound = 'tenant_not_found';
    case DefaultLocaleNotSupported = 'default_locale_not_supported';
    case TenantDomainNotFound = 'tenant_domain_not_found';
    case DomainAlreadyRegistered = 'domain_already_registered';
    case TenantDomainIsPrimary = 'tenant_domain_is_primary';
    case UnknownHost = 'unknown_host';
    case MissingTenantHeader = 'missing_tenant_header';
    case InvalidTenantHeader = 'invalid_tenant_header';
    case TenantAccessDenied = 'tenant_access_denied';
    case UnknownDomain = 'unknown_domain';
    case InvalidCredentials = 'invalid_credentials';
    case InvalidRefreshToken = 'invalid_refresh_token';
    case RefreshTokenReused = 'refresh_token_reused';
    case MissingCapability = 'missing_capability';
    case RoleNotEditable = 'role_not_editable';
    case RoleInUse = 'role_in_use';
    case RoleNameTaken = 'role_name_taken';
    case UnknownCapability = 'unknown_capability';
    case MembershipExists = 'membership_exists';
    case LastOwnerRemoval = 'last_owner_removal';
    case InvitationTokenInvalid = 'invitation_token_invalid';
    case InvitationTokenExpired = 'invitation_token_expired';
    case MfaRequired = 'mfa_required';
    case MfaCodeInvalid = 'mfa_code_invalid';
    case MfaAlreadyEnrolled = 'mfa_already_enrolled';
    case MfaNotEnrolled = 'mfa_not_enrolled';
    case MfaEnforcedForRole = 'mfa_enforced_for_role';
    case MfaEnforcementRequired = 'mfa_enforcement_required';
    case TenantMismatch = 'tenant_mismatch';
    case CustomerEmailTaken = 'customer_email_taken';
    case CustomerAlreadyClaimed = 'customer_already_claimed';
    case ClaimTokenInvalid = 'claim_token_invalid';
    case ClaimTokenExpired = 'claim_token_expired';
    case PasswordResetTokenInvalid = 'reset_token_invalid';
    case PasswordResetTokenExpired = 'reset_token_expired';
    case CatalogEventImmutable = 'catalog.event_immutable';
    case CatalogCurrencyMismatch = 'catalog.currency_mismatch';
    case CatalogEventNotPublishable = 'catalog.event_not_publishable';
    case CatalogEventNotCancelable = 'catalog.event_not_cancelable';
    case CatalogSeatMapDuplicateSeats = 'catalog.seat_map_duplicate_seats';
    case CatalogSeatMapNameTaken = 'catalog.seat_map_name_taken';
    case CatalogSeatMapConflict = 'catalog.seat_map_conflict';
    case CatalogSeatMapVenueMismatch = 'catalog.seat_map_venue_mismatch';
    case CatalogSeatMapVirtualEvent = 'catalog.seat_map_virtual_event';
    case CatalogSeatMapInUse = 'catalog.seat_map_in_use';
    case CatalogSeatMapRequired = 'catalog.seat_map_required';
    case InsufficientInventory = 'insufficient_inventory';
    case EventNotFound = 'event_not_found';
    case TicketTypeNotInEvent = 'ticket_type_not_in_event';
    case SalesWindowClosed = 'sales_window_closed';
    case HoldNotFound = 'hold_not_found';
    case HoldNotReleasable = 'hold_not_releasable';
    case HoldNotExtendable = 'hold_not_extendable';
    case HoldNotCommittable = 'hold_not_committable';
    case SeatSelectionInvalid = 'seat_selection_invalid';
    case SeatUnavailable = 'seat_unavailable';
    case EventNotSeated = 'event_not_seated';
    case SeatNotModifiable = 'seat_not_modifiable';
    case CheckoutHoldExpired = 'checkout.hold_expired';
    case HoldAlreadyConverted = 'hold_already_converted';
    case OrderNotFound = 'order_not_found';
    case OrderNotCancelable = 'order_not_cancelable';
    case OrderNotPaid = 'order_not_paid';
    case InvalidOrderTransition = 'invalid_order_transition';
    case PromoCodeInvalid = 'promo_code_invalid';
    case PromoCodeNotActive = 'promo_code_not_active';
    case PromoCodeExhausted = 'promo_code_exhausted';
    case PromoCodeCurrencyMismatch = 'promo_code_currency_mismatch';
    case PromoCodeImmutableField = 'promo_code_immutable_field';
    case IdempotencyKeyMissing = 'idempotency_key_missing';
    case IdempotencyKeyReuseMismatch = 'idempotency_key_reuse_mismatch';
    case OrderNotPayable = 'order_not_payable';
    case PaymentMethodNotAvailable = 'payment_method_not_available';
    case PaymentDeclined = 'payment_declined';
    case GatewayUnavailable = 'gateway_unavailable';
    case WebhookSignatureInvalid = 'webhook_signature_invalid';
    case WebhookUnparseable = 'webhook_unparseable';
    case RefundPaymentNotFound = 'refund_payment_not_found';
    case RefundNotFound = 'refund_not_found';
    case PaymentNotRefundable = 'payment_not_refundable';
    case RefundAmountExceedsRefundable = 'refund_amount_exceeds_refundable';
    case RefundCurrencyMismatch = 'refund_currency_mismatch';
    case RefundTicketsNotInOrder = 'refund_tickets_not_in_order';
    case GatewayUnknown = 'gateway_unknown';
    case GatewayNotEnabled = 'gateway_not_enabled';
    case GatewayNotConfigured = 'gateway_not_configured';
    case SubmerchantAlreadyOnboarded = 'submerchant_already_onboarded';
    case SubmerchantNotActive = 'submerchant_not_active';
    case CheckinNotAssigned = 'checkin_not_assigned';

    public function status(): int
    {
        return match ($this) {
            self::RequestNotFound => 404,
            self::RequestMethodNotAllowed => 405,
            self::RequestValidationFailed => 422,
            self::AuthUnauthenticated => 401,
            self::AuthForbidden => 403,
            self::RequestRateLimited => 429,
            self::PayloadTooLarge => 413,
            self::ServerInternalError => 500,
            self::HealthDegraded => 503,
            self::InvalidQueryParameter => 400,
            self::TenantNotFound => 404,
            self::DefaultLocaleNotSupported => 422,
            self::TenantDomainNotFound => 404,
            self::DomainAlreadyRegistered => 409,
            self::TenantDomainIsPrimary => 409,
            self::UnknownHost => 404,
            self::MissingTenantHeader => 400,
            self::InvalidTenantHeader => 400,
            self::TenantAccessDenied => 403,
            self::UnknownDomain => 404,
            self::InvalidCredentials => 401,
            self::InvalidRefreshToken => 401,
            self::RefreshTokenReused => 401,
            self::MissingCapability => 403,
            self::RoleNotEditable => 409,
            self::RoleInUse => 409,
            self::RoleNameTaken => 409,
            self::UnknownCapability => 422,
            self::MembershipExists => 409,
            self::LastOwnerRemoval => 409,
            self::InvitationTokenInvalid => 401,
            self::InvitationTokenExpired => 401,
            self::MfaRequired => 401,
            self::MfaCodeInvalid => 401,
            self::MfaAlreadyEnrolled => 409,
            self::MfaNotEnrolled => 409,
            self::MfaEnforcedForRole => 403,
            self::MfaEnforcementRequired => 403,
            self::TenantMismatch => 401,
            self::CustomerEmailTaken => 409,
            self::CustomerAlreadyClaimed => 409,
            self::ClaimTokenInvalid => 401,
            self::ClaimTokenExpired => 401,
            self::PasswordResetTokenInvalid => 401,
            self::PasswordResetTokenExpired => 401,
            self::CatalogEventImmutable => 409,
            self::CatalogCurrencyMismatch => 422,
            self::CatalogEventNotPublishable => 409,
            self::CatalogEventNotCancelable => 409,
            self::CatalogSeatMapDuplicateSeats => 422,
            self::CatalogSeatMapNameTaken => 422,
            self::CatalogSeatMapConflict => 409,
            self::CatalogSeatMapVenueMismatch => 422,
            self::CatalogSeatMapVirtualEvent => 422,
            self::CatalogSeatMapInUse => 409,
            self::CatalogSeatMapRequired => 409,
            self::InsufficientInventory => 409,
            self::EventNotFound => 404,
            self::TicketTypeNotInEvent => 422,
            self::SalesWindowClosed => 409,
            self::HoldNotFound => 404,
            self::HoldNotReleasable => 409,
            self::HoldNotExtendable => 409,
            self::HoldNotCommittable => 409,
            self::SeatSelectionInvalid => 422,
            self::SeatUnavailable => 409,
            self::EventNotSeated => 409,
            self::SeatNotModifiable => 409,
            self::CheckoutHoldExpired => 409,
            self::HoldAlreadyConverted => 409,
            self::OrderNotFound => 404,
            self::OrderNotCancelable => 409,
            self::OrderNotPaid => 409,
            self::InvalidOrderTransition => 409,
            self::PromoCodeInvalid => 422,
            self::PromoCodeNotActive => 422,
            self::PromoCodeExhausted => 422,
            self::PromoCodeCurrencyMismatch => 422,
            self::PromoCodeImmutableField => 422,
            self::IdempotencyKeyMissing => 400,
            self::IdempotencyKeyReuseMismatch => 409,
            self::OrderNotPayable => 409,
            self::PaymentMethodNotAvailable => 422,
            self::PaymentDeclined => 402,
            self::GatewayUnavailable => 503,
            self::WebhookSignatureInvalid => 401,
            self::WebhookUnparseable => 422,
            self::RefundPaymentNotFound => 404,
            self::RefundNotFound => 404,
            self::PaymentNotRefundable => 409,
            self::RefundAmountExceedsRefundable => 422,
            self::RefundCurrencyMismatch => 422,
            self::RefundTicketsNotInOrder => 422,
            self::GatewayUnknown => 422,
            self::GatewayNotEnabled => 409,
            self::GatewayNotConfigured => 409,
            self::SubmerchantAlreadyOnboarded => 409,
            self::SubmerchantNotActive => 409,
            self::CheckinNotAssigned => 403,
        };
    }

    public function title(): string
    {
        return match ($this) {
            self::RequestNotFound => 'Not found',
            self::RequestMethodNotAllowed => 'Method not allowed',
            self::RequestValidationFailed => 'Validation failed',
            self::AuthUnauthenticated => 'Unauthenticated',
            self::AuthForbidden => 'Forbidden',
            self::RequestRateLimited => 'Too many requests',
            self::PayloadTooLarge => 'Payload too large',
            self::ServerInternalError => 'Internal server error',
            self::HealthDegraded => 'Service degraded',
            self::InvalidQueryParameter => 'Invalid query parameter',
            self::TenantNotFound => 'Tenant not found',
            self::DefaultLocaleNotSupported => 'Default locale not supported',
            self::TenantDomainNotFound => 'Tenant domain not found',
            self::DomainAlreadyRegistered => 'Domain already registered',
            self::TenantDomainIsPrimary => 'Tenant domain is primary',
            self::UnknownHost => 'Unknown host',
            self::MissingTenantHeader => 'Missing tenant header',
            self::InvalidTenantHeader => 'Invalid tenant header',
            self::TenantAccessDenied => 'Tenant access denied',
            self::UnknownDomain => 'Unknown domain',
            self::InvalidCredentials => 'Invalid credentials',
            self::InvalidRefreshToken => 'Invalid refresh token',
            self::RefreshTokenReused => 'Refresh token reused',
            self::MissingCapability => 'Missing capability',
            self::RoleNotEditable => 'Role not editable',
            self::RoleInUse => 'Role in use',
            self::RoleNameTaken => 'Role name taken',
            self::UnknownCapability => 'Unknown capability',
            self::MembershipExists => 'Membership exists',
            self::LastOwnerRemoval => 'Last owner removal',
            self::InvitationTokenInvalid => 'Invitation token invalid',
            self::InvitationTokenExpired => 'Invitation token expired',
            self::MfaRequired => 'MFA required',
            self::MfaCodeInvalid => 'MFA code invalid',
            self::MfaAlreadyEnrolled => 'MFA already enrolled',
            self::MfaNotEnrolled => 'MFA not enrolled',
            self::MfaEnforcedForRole => 'MFA enforced for role',
            self::MfaEnforcementRequired => 'MFA enforcement required',
            self::TenantMismatch => 'Tenant mismatch',
            self::CustomerEmailTaken => 'Customer email taken',
            self::CustomerAlreadyClaimed => 'Customer already claimed',
            self::ClaimTokenInvalid => 'Claim token invalid',
            self::ClaimTokenExpired => 'Claim token expired',
            self::PasswordResetTokenInvalid => 'Password reset token invalid',
            self::PasswordResetTokenExpired => 'Password reset token expired',
            self::CatalogEventImmutable => 'Event immutable',
            self::CatalogCurrencyMismatch => 'Currency mismatch',
            self::CatalogEventNotPublishable => 'Event not publishable',
            self::CatalogEventNotCancelable => 'Event not cancelable',
            self::CatalogSeatMapDuplicateSeats => 'Duplicate seats',
            self::CatalogSeatMapNameTaken => 'Seat map name taken',
            self::CatalogSeatMapConflict => 'Seat map conflict',
            self::CatalogSeatMapVenueMismatch => 'Seat map venue mismatch',
            self::CatalogSeatMapVirtualEvent => 'Seat map virtual event',
            self::CatalogSeatMapInUse => 'Seat map in use',
            self::CatalogSeatMapRequired => 'Seat map required',
            self::InsufficientInventory => 'Insufficient inventory',
            self::EventNotFound => 'Event not found',
            self::TicketTypeNotInEvent => 'Ticket type not in event',
            self::SalesWindowClosed => 'Sales window closed',
            self::HoldNotFound => 'Hold not found',
            self::HoldNotReleasable => 'Hold not releasable',
            self::HoldNotExtendable => 'Hold not extendable',
            self::HoldNotCommittable => 'Hold not committable',
            self::SeatSelectionInvalid => 'Seat selection invalid',
            self::SeatUnavailable => 'Seat unavailable',
            self::EventNotSeated => 'Event not seated',
            self::SeatNotModifiable => 'Seat not modifiable',
            self::CheckoutHoldExpired => 'Hold expired',
            self::HoldAlreadyConverted => 'Hold already converted',
            self::OrderNotFound => 'Order not found',
            self::OrderNotCancelable => 'Order not cancelable',
            self::OrderNotPaid => 'Order not paid',
            self::InvalidOrderTransition => 'Invalid order transition',
            self::PromoCodeInvalid => 'Promo code invalid',
            self::PromoCodeNotActive => 'Promo code not active',
            self::PromoCodeExhausted => 'Promo code exhausted',
            self::PromoCodeCurrencyMismatch => 'Promo code currency mismatch',
            self::PromoCodeImmutableField => 'Promo code immutable field',
            self::IdempotencyKeyMissing => 'Idempotency key missing',
            self::IdempotencyKeyReuseMismatch => 'Idempotency key reuse mismatch',
            self::OrderNotPayable => 'Order not payable',
            self::PaymentMethodNotAvailable => 'Payment method not available',
            self::PaymentDeclined => 'Payment declined',
            self::GatewayUnavailable => 'Gateway unavailable',
            self::WebhookSignatureInvalid => 'Webhook signature invalid',
            self::WebhookUnparseable => 'Webhook unparseable',
            self::RefundPaymentNotFound => 'Payment not found',
            self::RefundNotFound => 'Refund not found',
            self::PaymentNotRefundable => 'Payment not refundable',
            self::RefundAmountExceedsRefundable => 'Refund amount exceeds refundable',
            self::RefundCurrencyMismatch => 'Refund currency mismatch',
            self::RefundTicketsNotInOrder => 'Refund tickets not in order',
            self::GatewayUnknown => 'Gateway unknown',
            self::GatewayNotEnabled => 'Gateway not enabled',
            self::GatewayNotConfigured => 'Gateway not configured',
            self::SubmerchantAlreadyOnboarded => 'Submerchant already onboarded',
            self::SubmerchantNotActive => 'Submerchant not active',
            self::CheckinNotAssigned => 'Not assigned to event',
        };
    }

    public function type(): string
    {
        return '/problems/'.str_replace(['.', '_'], '-', $this->value);
    }
}
